"""stock_moves created_at

Revision ID: 87fc548207dd
Revises: 0fbef5144dfd
Create Date: 2026-02-07 20:11:38.183059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '87fc548207dd'
down_revision: Union[str, None] = '0fbef5144dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table("stock_moves") as batch_op:
    batch_op.add_column(
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        )
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_moves', 'created_at')
    # ### end Alembic commands ###
