"""stock qty + stock moves

Revision ID: cb69ddb6b888
Revises: e1a23b0f88a9
Create Date: 2026-02-07 19:27:45.054973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cb69ddb6b888'
down_revision: Union[str, None] = 'e1a23b0f88a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_moves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_moves_product_id'), 'stock_moves', ['product_id'], unique=False)
    op.add_column('products', sa.Column('stock_qty', sa.Integer(), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_qty')
    op.drop_index(op.f('ix_stock_moves_product_id'), table_name='stock_moves')
    op.drop_table('stock_moves')
    # ### end Alembic commands ###
